---
title: "Traffic Collisions Exploratory Analysis"
output: html_document
date: "2026-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(jsonlite)
library(readxl)
library(forecast)
library(tseries)
```

# Metro Bike Share Trips
```{r cars}
bike_share_trips_df <- read.csv('Data/Metro_Bike_Share_Trip_Data.csv')
bike_share_trips_cleaned <- bike_share_trips_df %>% rename(
  TripKey = `Trip.ID`,
  TripDuration = Duration,
  TripStartTime = `Start.Time`,
  TripEndTime = `End.Time`,
  StartingStationKey = `Starting.Station.ID`,
  StartingStationLatitude = `Starting.Station.Latitude`,
  StartingStationLongitude = `Starting.Station.Longitude`,
  EndingStationKey = `Ending.Station.ID`,
  EndingStationLatitude = `Ending.Station.Latitude`,
  BikeKey = `Bike.ID`,
  PlanDuration = `Plan.Duration`,
  TripRouteCategory = `Trip.Route.Category`,
  PassholderType = `Passholder.Type`,
) %>% mutate(
  TripStartTime = as_datetime(TripStartTime, format='%m/%d/%Y %I:%M:%S %p'),
  TripEndTime = as_datetime(TripEndTime, format='%m/%d/%Y %I:%M:%S %p')
) %>% rowwise() %>% mutate(
  StartingLatitude = as.numeric(str_split(gsub('\\)', '', gsub('\\(', '', `Starting.Lat.Long`)), ', ')[[1]][[1]]),
  StartingLongitude = as.numeric(tail(str_split(gsub('\\)', '', gsub('\\(', '', `Starting.Lat.Long`)), ',')[[1]], n=1)),
  EndingLatitude = as.numeric(str_split(gsub('\\)', '', gsub('\\(', '', `Ending.Lat.Long`)), ',')[[1]][[1]]),
  EndingLongitude = as.numeric(tail(str_split(gsub('\\)', '', gsub('\\(', '', `Ending.Lat.Long`)), ',')[[1]], n=1)),
) %>% select(
  -`Starting.Lat.Long`, -`Ending.Lat.Long`
)

print(
  bike_share_trips_cleaned %>% group_by(TripStartDate = as.Date(TripStartTime)) %>%
    summarise(BikeTrips = n()) %>% ggplot(aes(x=TripStartDate, y=BikeTrips)) +
    geom_line()
)
```
```{r}
bike_share_by_coordinates <- bike_share_trips_cleaned %>% 
  group_by(Latitude = floor(StartingStationLatitude*100)/100, 
           Longitude = floor(StartingStationLongitude*100)/100) %>%
  summarise(Count = n()) %>%
  filter(!is.na(Latitude), !is.na(Longitude),
         Latitude != 0, Longitude != 0)

print(
  bike_share_by_coordinates %>% 
    arrange(Count) %>%
    ggplot(aes(x=Longitude, y=Latitude, color=Count)) +
    geom_point(size=4) +
    ggtitle(paste0('Bike Share Trips by Coordinates in ', year, sep=''))
)
```

# Trying LADOT again
No coordinates, spotty time coverage and probably spotty geo coverage
```{r}
ladot_traffic_df <- read.csv('Cleaned Data/LADOTTrafficCounts.csv')

ladot_traffic_df %>% group_by(PrimaryStreet, CrossStreet) %>%
  summarise(n())

ladot_traffic_df %>% select(CountDate) %>% distinct() %>% arrange(CountDate)
```


# LA Census Data and other data
```{r}
# by ZIP code, no surprise; need to figure out which ZIP code each unique set of coordinates is in
# census_2010_df <- read.csv('../LA Data/Reference/2010_Census_Populations_by_Zip_Code.csv')

# by split tract; will need a whole new dataset about the split tract locations; probably not worth
# extensive data, though
census_2023_df <- read.csv('../LA Data/Reference/2023_Population_and_Poverty_by_Split_Tract_-8870005362651359077.csv')

# extensive data; will need to look up geography of council districts
# council districts are big, should be good for chunking into large groups

census_by_council_dist <- read.csv('../LA Data/Reference/Census_Data_by_Council_District.csv')

# by lat/lon; draw up map and compare w/ collisions data
# wait, this doesn't tell me availability, just where parking meters are?
# ladot_parking_df <- read.csv('Cleaned Data/LADOTParkingInventory.csv')

# by metro line; need to look up geography and figure out how to compare w/ static points
# metro_ridership <- read.csv('Data/metro_ridership.csv')

```

s

